---
name: module3_task2

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  module3_task2:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: run setup.sh
        run: |
          cd module3_task1
          chmod u+x setup.sh
          sudo ./setup.sh
      - name: Run all those makefile commands that I spent ages making
        run: |
          cd module3_task1
          make help
          make build
          make run
          make stop
          make clean

      - name: create zip file with make package
        run: |
          cd module3_task2 && make package
      - name: run tests
        run: |
          cd module3_task2/awesome-api && make unit-tests
          cd module3_task2/awesome-api && make integration-tests
          cd module3_task2 && make validate
      - name: Archive zip file if the tests pass
        if: ${{github.ref=='refs/heads/master'}}
        uses: actions/upload-artifact@v3
        with:
          name: Save zip file
          path: module3_task2/awesome-website.zip
            cd module3_task2 && make package