---
name: module3_task1

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  module3_task1:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: run setup.sh
        run: |
          cd module3_task1
          chmod u+x setup.sh
          sudo ./setup.sh
      - name: Run all those makefile commands that I spent ages making
        run: |
          cd module3_task1
          make help
          make build
          make run
          make stop
          make clean
