---
name: module3_task0

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  module3_task0:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: cd make help
        run: |
          cd module3_task0
          make help
